### ISSUE TITLE
Azimuth and Elevation value isn't even close

### ISSUE THREAD

**Issue by shaaahan** [G6EJD/ESP32_2D_Sun_Tracker#1]
Hey! Thanks for making such a great project and am sorry for creating an issue here, but I don't know how to ask for help without creating one.

I am trying to use this code with my esp32 using my location data, but I am getting wrong elevation and azimuth values, then I tried with your data(only changed my wifi credentials) and the value I get is also not the same comparing with suncalc and NOAA, even it shows elevation at negative 10 degrees when it is 7 o clock at your location, which doesn't match at all. I need this code to work with my board, can you please help me? 

edit: it prints the correct local time in the serial monitor

**Comment by aGGreSSiv** [comment]
Yes, I tried to do this project too.  but I couldn't succeed.  Maybe I'll get some code as a result of these conversations :)

**Comment by G6EJD** [comment]
When you say local time do you mean my local time or yours? Eg I’m currently at 09:50 GMT/UTC

**Comment by shaaahan** [comment]
I tried mine and, it showed the right time, then I tried your latitude, longitude value, with your timezone, and it printed the right local time of yours( I checked with google- Bath, England). But everytime it prints the wrong azimuth and elevation value.

**Comment by shaaahan** [comment]
I tried your code again, just changed wifi credentials, it worked fine. But when I tried it with my location data, and timezone- the local time was accurate, but the azimuth value was 270  ( 240 in suncalc), elevation -72 ( 6 in suncalc). Can you please help me with the code?

**Comment by G6EJD** [comment]
Ok, can you post your time zone or nearest city so I can get lat/lon and then I can check the code.

**Comment by shaaahan** [comment]
You can use this link for my lat n lon- https://maps.app.goo.gl/1hsDNpNCHHMJ9j9EA
My timezone is Dhaka/Asia or GMT +6, this works fine ig - 

configTime(0, 0, "asia.pool.ntp.org", "time.nist.gov");
setenv("TZ", "<+06>-6", 1);

**Comment by G6EJD** [comment]
New version added using the Arduino SunCalculator Library

**Comment by aGGreSSiv** [comment]
Hello
There used to be no library below.

```
#include <SolarCalculator.h>
```
 I downloaded this library from the address in the [link](https://github.com/jpb10/SolarCalculator). I'm getting an error like this:

```
Compilation error: 'sun_elevation' was not declared in this scope
```
Did I install the wrong library? where am i making a mistake?

**Comment by shaaahan** [comment]
No, the sun_elevation was a variable declared in the previous version. You can change "sun_elevation" to "el" and it will compile fine. However, the values were off by 100 or were negative where elevation was a positive value in real life. I really don't understand this, it works fine with his location variable but not mine, haha. 

@G6EJD you used a negative sign in my longitude value, which I didn't understand why. I tried both with positive and negative values, but it didn't work again.

Then I further investigated the solar calculator library and found an example code, which in my case worked fine. It printed the correct values. Tho it doesn't print the time, date and stuff, but I don't need it for my use, so I didn't care to edit the code to get those values.


```
#include <ESP32Servo.h>
#include <SolarCalculator.h> // https://github.com/jpb10/SolarCalculator
#include <TimeLib.h> //https://github.com/PaulStoffregen/Time

// Assigning Servo Pins
#define elevation_servo 25
#define azimuth_servo 32

// Location Variables
double latitude = 25.1062;   // Enter your latitude
double longitude = 89.0199;  // Enter your longitude
double az, el;

int utc_offset = +6;  // Change this according to your local time's offset to UTC

// Creating Servo Object
Servo Azi_servo;
Servo Ele_servo;

void setup() {
  Serial.begin(115200);

  // Set system time to compile time
  setTime(toUtc(compileTime()));

  // Servo Setup
  Azi_servo.attach(azimuth_servo);
  Ele_servo.attach(elevation_servo);

  test_azimuth();
  delay(1000);
  test_elevation();
  delay(1000);
}

void loop() {

  time_t utc = now();

  calcHorizontalCoordinates(utc, latitude, longitude, az, el);
  Serial.println("Az: " + String(az) + "  El: " + String(el));

  Azi_servo.write(map(az, 90, 270, 180, 0));
  if (el < 0) el = 0;
  Ele_servo.write(145 - el);

  delay(1 * 60 * 1000);  // You can change this according to your use
}

/////////////////////////////////////////////////////////////////////////////////////////////////////////

time_t toUtc(time_t local) {
  return local - utc_offset * 3600L;
}

/////////////////////////////////////////////////////////////////////////////////////////////////////////

time_t compileTime() {
  const uint8_t COMPILE_TIME_DELAY = 8;
  const char *compDate = __DATE__, *compTime = __TIME__, *months = "JanFebMarAprMayJunJulAugSepOctNovDec";
  char chMon[4], *m;
  tmElements_t tm;

  strncpy(chMon, compDate, 3);
  chMon[3] = '\0';
  m = strstr(months, chMon);
  tm.Month = ((m - months) / 3 + 1);

  tm.Day = atoi(compDate + 4);
  tm.Year = atoi(compDate + 7) - 1970;
  tm.Hour = atoi(compTime);
  tm.Minute = atoi(compTime + 3);
  tm.Second = atoi(compTime + 6);
  time_t t = makeTime(tm);
  return t + COMPILE_TIME_DELAY;
}

/////////////////////////////////////////////////////////////////////////////////////////////////////////

void test_azimuth() {
  Azi_servo.write(90);  // Centre position
  delay(500);
  Azi_servo.write(60);  // Centre position
  delay(500);
  Azi_servo.write(120);  // Centre position
  delay(500);
  Azi_servo.write(90);  // Centre position
  delay(500);
}

/////////////////////////////////////////////////////////////////////////////////////////////////////////

void test_elevation() {
  for (int a = 5; a < 145; a = a + 2) {
    Ele_servo.write(a);  // Centre position
    delay(30);
  }
  Ele_servo.write(145);  // Centre position
  delay(1000);
}
```

One thing, is that I didn't test it with servos yet, but it should work fine ig.

**Comment by aGGreSSiv** [comment]
Sometimes I regret that I'm not a software developer. Thanks for your help. Now I will set up the test environment and try again.

**Comment by G6EJD** [comment]
The negative sign was a test for west of Greenwich, I left it in by mistake. None of the ESP32 sun calculators give the same results as SunCalc, but which is wrong?

**Comment by shaaahan** [comment]
> Sometimes I regret that I'm not a software developer. Thanks for your help. Now I will set up the test environment and try again.

Lol, I regret that too, I have just developed some understanding after following so many tutorials. So the code I wrote above does work, but has one great problem. It gets out of sync if you press the reset button, or you lose power. I mean say, you uploaded the code at 7:15 pm, and you lose power at 7:20 pm, then if the power comes back at 7:25 pm, it doesn't start from 7:25 pm instead it starts from 7:15 pm and stays out of sync. And I think that's a major problem.

Ignore this if you don't want to hear me blabbing-
So, being a noob at this, I asked chatgpt, if there was any way I could get over this problem. It suggested that I might use an RTC module or smtn, but I DONT WANT TO! Then I asked again if there was any way I could bypass the problem without using an RTC device, and it suggested using an NTP client, which @G6EJD used in his version. However now with an NTP client library, it is easier ig. However, the code it provided didn't work right away. There was a small but BIG:') problem. It didn't take into account the UTC offset in the loop. And I was getting the wrong values again. I was on the verge of giving up after trying so many things. And my dumb gpt couldn't figure out anything. So, I tried debugging the local time from the original example of the Solar Calculator Library, and et voila, I found the problem that was causing the problem. Just had to add "time_t utc = local - utcOffsetInSeconds; " this thing and my 5 hours shittiness finally came to life haha. Thanks again to @G6EJD for creating such a great project that too maybe 7 years ago.

And the reason I talked all this shitt is because...idk:') Things are easier now, tho gpt won't write you everything like  I added the wifi setup the way I generally use, ntp client and things, but maybe help you find the problem or show you some way @aGGreSSiv 

I will add the code below in another comment, and @G6EJD maybe you can add this code to the v2.

**Comment by shaaahan** [comment]
> The negative sign was a test for west of Greenwich, I left it in by mistake. None of the ESP32 sun calculators give the same results as SunCalc, but which is wrong?

I understand that it won't provide the exact values but, my values were not even close haha. Elevation in real life was 56 or smtn, and it showed -21 in the serial monitor.

**Comment by shaaahan** [comment]
I tried to add some comments where you need to change things.

```
#include <ESP32Servo.h>
#include <WiFi.h>
#include <NTPClient.h>
#include <WiFiUdp.h>
#include <SolarCalculator.h>
#include <TimeLib.h>

// WIFI
#define WLAN_SSID "change it with yours"
#define WLAN_PASS "change it with yours"

WiFiClient client;

// Assigning Servo Pins
#define elevation_servo 25
#define azimuth_servo 32

// Location Variables
double latitude = 25.000;   // Enter your latitude
double longitude = 89.000;  // Enter your longitude
double az, el;

int utc_offset = +6;  // Change this according to your local time's offset to UTC

// NTP settings
const char* ntpServer = "asia.pool.ntp.org";  // I used a server which is close to my country, you can change it too "pool.ntp.org"
const int utcOffsetInSeconds = utc_offset * 3600;
WiFiUDP ntpUDP;
NTPClient timeClient(ntpUDP, ntpServer, utcOffsetInSeconds);

// Creating Servo Object
Servo Azi_servo;
Servo Ele_servo;

void setup() {
  Serial.begin(115200);

  // Connection to WiFi access point.
  {
    Serial.println();
    Serial.println();
    Serial.print("Connecting to ");
    Serial.println(WLAN_SSID);

    WiFi.mode(WIFI_STA);
    WiFi.begin(WLAN_SSID, WLAN_PASS);
    while (WiFi.status() != WL_CONNECTED) {
      delay(500);
      Serial.print(".");
    }
    Serial.println();
    Serial.println("WiFi connected!");
    Serial.println("IP address: ");
    Serial.println(WiFi.localIP());
    Serial.println();
  }

  // Servo Setup
  Azi_servo.attach(azimuth_servo);
  Ele_servo.attach(elevation_servo);

  // Perform initial time synchronization
  Serial.print("Synchronizing time");
  syncTime();
  Serial.println("Time synchronized");

  test_azimuth();
  delay(1000);
  test_elevation();
  delay(1000);
}

void loop() {

  // Update time from NTP server
  timeClient.update();

  if (timeClient.getMinutes() % 10 == 0) {
    Serial.println("Time synchronized");
  }

  time_t local = timeClient.getEpochTime();
  time_t utc = local - utcOffsetInSeconds;  // I subtracted because my offset is positive, maybe you have to add if yours is negative

  // Convert UTC to local time
  tmElements_t localTime;
  breakTime(local, localTime);

  Serial.print("Local date and time: ");
  Serial.print(localTime.Year + 1970);  // Adjust for the epoch
  Serial.print("-");
  Serial.print(localTime.Month);
  Serial.print("-");
  Serial.print(localTime.Day);
  Serial.print(" ");
  Serial.print(localTime.Hour);
  Serial.print(":");
  Serial.print(localTime.Minute);
  Serial.print(":");
  Serial.println(localTime.Second);

  // Calculate the solar position, in degrees
  calcHorizontalCoordinates(utc, latitude, longitude, az, el);
  Serial.println("Az: " + String(az) + "  El: " + String(el));

  // Adjust Servo
  Azi_servo.write(map(az, 90, 270, 180, 0));   // Align to azimuth
  if (el < 0) el = 0;                                         // Point at horizon if less than horizon
  Ele_servo.write(145 - el);                            // map(value, fromLow, fromHigh, toLow, toHigh)

  delay(1 * 60 * 1000);                                  // Wait 1-minute then check position again
}

void syncTime() {
  while (!timeClient.update()) {
    Serial.print(".");
    timeClient.forceUpdate();
    delay(100);
  }
  Serial.println();
}

void test_azimuth() {
  Azi_servo.write(90);  // Centre position
  delay(500);
  Azi_servo.write(60);  // Centre position
  delay(500);
  Azi_servo.write(120);  // Centre position
  delay(500);
  Azi_servo.write(90);  // Centre position
  delay(500);
}

void test_elevation() {
  for (int a = 5; a < 145; a = a + 2) {
    Ele_servo.write(a);  // Centre position
    delay(30);
  }
  Ele_servo.write(145);  // Centre position
  delay(1000);
}
```

**Comment by shaaahan** [comment]
@aGGreSSiv  I will close the issue, if it works okay with your setup

**Comment by aGGreSSiv** [comment]
I can't test it right away, but I'll let you know when I do.  We can close it for now.  Thank you for your support
